name: Custom Branch Checks

on:
  push:
    branches:
      - '*'

jobs:
  check_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Name
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ ! $branch_name =~ ^master$ && ! $branch_name =~ ^development$ && ! $branch_name =~ ^feature/.*$ ]]; then
            echo "Branch name does not match allowed pattern."
            exit 1
          fi
